language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
   - pip install Django==$DJANGO
   - pip install -r dev_requirements.txt
   - pip freeze
   - python setup.py develop
env:
  - DJANGO="1.8.5"
  - DJANGO="1.9.2"
  - DJANGO="1.10"
script: python setup.py nosetests
services:
  - redis-server
