language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
matrix:
  exclude:
    - python: "3.3"
      env: DJANGO="1.4.11"
    - python: "3.3"
      env: DJANGO="1.9.2"
    - python: "3.4"
      env: DJANGO="1.4.11"
install:
   - pip install Django==$DJANGO
   - pip install -r dev_requirements.txt
   - pip freeze
   - python setup.py develop
env:
  - DJANGO="1.4.11"
  - DJANGO="1.5.5"
  - DJANGO="1.6.10"
  - DJANGO="1.7.4"
  - DJANGO="1.8.5"
  - DJANGO="1.9.2"
script: python setup.py nosetests
services:
  - redis-server
