language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="1.7.4"
    - python: "2.6"
      env: DJANGO="1.8.5"
install:
   - pip install Django==$DJANGO
   - pip install -r dev_requirements.txt
   - pip freeze
   - python setup.py develop
env:
  - DJANGO="1.4.10"
  - DJANGO="1.5.1"
  - DJANGO="1.6.2"
  - DJANGO="1.7.4"
  - DJANGO="1.8.5"
script: python setup.py nosetests
services:
  - redis-server
